### ISSUE TITLE
gradle jar komennolla muodostettu jar-tiedosto ei toimi

### ISSUE THREAD

**Issue by nikomn** [VirtualAkseli/Lukuvinkkikirjasto-Napsa#21]
Suoritus kaatuu gson aiheiseen virheilmoitukseen:

```
Lukuvinkkikirjasto-Napsa > java -jar build/libs/Lukuvinkkikirjasto-Napsa.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/Gson                                                                   
        at dao.LukuvinkkiDao.<init>(LukuvinkkiDao.java:20)                                                                                        
        at Main.main(Main.java:11)                                                                                                                
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson                                                                                 
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)                                                
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)                                             
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)                                                                        
        ... 2 more                
```

Oletettavasti build.gradle tiedostoon pitäisi lisätä jotain, että gson pakkataan jar tiedoston sisään.

**Comment by VirtualAkseli** [comment]
Ongelmana on se, että suoritusaikaiset riippuvuudet tuon GSON:n osalta tulee määritellä erillisen pluginin kautta. Teen PR:n asiasta, sain -jar:n toimimaan. Tämä aiheuttaa pieniä muutoksia ohjeistukseen mutta korjaan ne samalla.
